### ISSUE TITLE
Pointer not visible when error MessageBox is displayed

### ISSUE THREAD

**Issue by coreyp1** [ryanries/GameB#11]
I ran across this when first trying to compile and run the game.  The assets did not copy, so I was given the error message, "The asset file was not found! It must reside in the same directory as the game executable."

The problem is that there is a message box, but the pointer is still hidden, so you can't click on the "OK" button.  Of course, escape or enter will dismiss the dialog and the game will exit, but that is not obvious.

**Comment by ryanries** [comment]
I do believe I have fixed this issue. Once we have created the main game window, the cursor gets hidden in the WndProc WM_ACTIVATE message with ShowCursor(FALSE). So in every situation where we fail after the window has been created, I added a ShowCursor(TRUE) right before the MessageBox is displayed. Please re-open this issue if you feel this has not been properly fixed. Thanks!
