### ISSUE TITLE
F1 key toggles debug, but it also opens my computer's help

### ISSUE THREAD

**Issue by coreyp1** [ryanries/GameB#12]
The default behavior of my computer is that, when I press F1, a browser opens and searches for "how to get help in windows".

Stupid, I know.  I've never looked into disabling it.

F1 should toggle the debug info, and it does, but the "help" browser search also opens on top of the game, which is annoying.

Perhaps the WM_KEYDOWN message needs to be caught?

**Comment by ryanries** [comment]
I'm thinking about this. I think it might be a smarter thing to just change which key/combo we use to toggle debug stats, rather than trying to intercept built-in Windows shortcuts.

**Comment by coreyp1** [comment]
Perhaps, but maybe the key presses that we process should always be caught anyways.  There might be others that cause problems down the road.  But I'm not convinced that I have a good solution for it, either.

**Comment by ryanries** [comment]
Resolved this issue by adding  a gDebugKey global variable, and a DebugKey registry setting under HKCU\\GAME_B\\, which you can configure to any virtual key you like.  E.g. 0x70 == VK_F1... 0x71 == VK_F2, and so on... so if you set the DebugKey registry setting to 0x72 hex, the debug hud will toggle with the F2 key.
