### ISSUE TITLE
Just a message from a vewer.

### ISSUE THREAD

**Issue by Dulipan** [ryanries/GameB#18]
Hello Ryan.. I have a new version of your game.. I did not release and I do not intend to.. but if you want and have time ,you can throw an eye on it and see if you like it. I also gave you access to my private repository. You can download hole project (recommanded: since I have added more files) or you can just download the prerelease ver. of the game and you need to download only 3 files the assets.dat, the game.exe and the fileList.txt. By the way this is not far a final product. I intend to add more maps and more monsters , other features, and well there are still small bugs and issues with the code. If you like it and wanna take some of my code to implement in your original game some of the features I added you can do so.. or if you love what I just did you can continue make your youtube series with my ideas. and can also copy files from the project and add to your game. Thanks to your series I learned a tone of C programming and develop my skills a lot. Chears .. and hope to hear you soon.
A final word .. I just forgot to mention that some of the assets are from other game copied.. voices music.. I do NOT intend to release the game with those assets.. they are temporarly just for test in game. If you copy and use it in your game I sugest to use them only for testing.

**Comment by ryanries** [comment]
@Dulipan I don't know why, but Github linked this message to the "mouse input" issue below this. Please see that thread for my reply.

**Comment by Dulipan** [comment]
Ahh maybe because my fault.. :D ? I was sending you a message through that issues , when instead I corrected that and create another issue.
